server:
  port: 10010

spring:
  application:
    name: api-gateway
  redis:
    host: r-bp17p9jz962ps2lc10pd.redis.rds.aliyuncs.com
    password: 041801slQQ

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5

zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    upload-service: /upload/**
    search-service: /search/**
    page-service: /page/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service:
      serviceId: cart-service
      path: /cart/**
      stripPrefix: false
    order-service:
      serviceId: order-service
      path: /order/**
      stripPrefix: false

  sensitive-headers:


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000 # 熔断超时时长：6000ms

ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试

ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
    allowCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
  jwt:
    publicFilePath: E:/rsa/id_rsa.pub
    user:
      expire: 30 # 过期时间,单位分钟
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
    app:
      id: 7 #微服务id
      secret: ${spring.application.name} #微服务密码
      expire: 1500 #微服务Jwt Token 过期时间 单位时间为分钟
      headName: appToken

  filter:
    allowPaths:
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

