server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 106.15.232.107
    port: 5672
    username: leyou
    password: leyou
    virtual-host: /leyou


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    com.leyou: debug

ly:
  page:
    itemDir: D:/nginx-1.13.8/html/item
    itemTemplate: item


